In [61]:
import numpy as np
from numpy import linalg

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [29]:
N = 10

array_1 = np.full(N, N-1) - np.arange(0, N)
array_1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [45]:
N = 7

array_2 = np.diag(np.full(N, N-1)) - np.diag(np.arange(0, N))
array_2

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [56]:
array_2.sum()

21

In [57]:
#поуниверсальнее, на случай если матрица - не диагональная

sum_diag = sum(array_2[i][i] for i in range(len(array_2)))
sum_diag

21

## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [63]:
a = np.array ( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array ( [4, 12, -3] )

In [64]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [68]:
4 * 0.466 + 2 * 3.844 - 5.555

3.997

## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [69]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [70]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [82]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [83]:
cos = 0
i = 0

for user in users_stats:
    i += 1
    cos_ = cosine(user, next_user_stats)
    
    if cos_ > cos:
        user_id = i
        cos = cos_

In [84]:
print('Наиболее похожий пользователь с номером',user_id)

Наиболее похожий пользователь с номером 8
