In [3]:
import numpy as np

# Задание

* Создайте случайную матрицу А1 размерностью 5 на 5
* Транспонируйте матрицу A1
* Найдите обратную матрицу для А1
* Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4
* Создайте нулевую матрицу размерности 3 на 3
* Для всех полученных матриц найдите: определитель, ранг и собственные значения
* Проанализируйте результаты

#### Создайте случайную матрицу А1 размерностью 5 на 5

In [5]:
A1 = np.random.random((5,5))
A1

array([[0.21743489, 0.06937727, 0.94033861, 0.1042091 , 0.5403797 ],
       [0.66066124, 0.22140834, 0.60298048, 0.46633729, 0.31146004],
       [0.43930655, 0.4802107 , 0.29349281, 0.3864864 , 0.7103176 ],
       [0.45353284, 0.88364668, 0.72353706, 0.74359784, 0.66159059],
       [0.51081875, 0.08182166, 0.48233263, 0.68563243, 0.06851409]])

#### Транспонируйте матрицу A1

In [6]:
A1.T

array([[0.21743489, 0.66066124, 0.43930655, 0.45353284, 0.51081875],
       [0.06937727, 0.22140834, 0.4802107 , 0.88364668, 0.08182166],
       [0.94033861, 0.60298048, 0.29349281, 0.72353706, 0.48233263],
       [0.1042091 , 0.46633729, 0.3864864 , 0.74359784, 0.68563243],
       [0.5403797 , 0.31146004, 0.7103176 , 0.66159059, 0.06851409]])

#### Найдите обратную матрицу для А1

In [8]:
A1_ = np.linalg.inv(A1)
A1_

array([[-0.953974  ,  3.45997314, -0.07763518, -0.61075422, -1.502177  ],
       [-0.92330386,  1.72260251, -1.52034583,  1.79518407, -2.12125197],
       [ 0.88917377,  0.49578372, -1.43715184,  0.61773315, -0.33220107],
       [ 0.11715579, -2.94139195,  0.99697045, -0.08960291,  2.9765002 ],
       [ 0.78306127, -1.90886725,  2.53502122, -1.04239034,  0.8808537 ]])

In [18]:
#Проверим результат
A1_1 = A1 @ A1_
A1_1.round()

array([[ 1.,  0.,  0., -0., -0.],
       [-0.,  1., -0., -0., -0.],
       [-0., -0.,  1., -0., -0.],
       [-0.,  0.,  0.,  1., -0.],
       [-0.,  0., -0., -0.,  1.]])

Получилось неплохо. Есть небольшие минусы, но вероятно это не критично

#### Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [29]:
A2 = np.random.random((4,4))
A2

array([[0.86180382, 0.05530644, 0.09250022, 0.54067593],
       [0.25868344, 0.64838471, 0.15134282, 0.95909987],
       [0.28146542, 0.30068453, 0.45243131, 0.29845918],
       [0.88021427, 0.37290958, 0.23401926, 0.11824329]])

In [30]:
I  = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
A3 = A2 * I
A3

array([[0.86180382, 0.        , 0.        , 0.        ],
       [0.        , 0.64838471, 0.        , 0.        ],
       [0.        , 0.        , 0.45243131, 0.        ],
       [0.        , 0.        , 0.        , 0.11824329]])

#### Создайте нулевую матрицу размерности 3 на 3

In [32]:
A4 = np.zeros((3,3))
A4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Для всех полученных матриц найдите: определитель, ранг и собственные значения

In [50]:
matrixs = [A1, A3, A4]

for i, m in enumerate(matrixs):
    det = np.linalg.det(m)
    rank = np.linalg.matrix_rank(m)
    eigval = np.linalg.eigvals(m)
    print('Для матрицы A', i+1, ' : определитель - ', round(det,  3), ', ранг - ', rank, ', собственные значения - ', eigval.round(2))

Для матрицы A 1  : определитель -  0.054 , ранг -  5 , собственные значения -  [ 2.36+0.j   -0.52+0.2j  -0.52-0.2j   0.11+0.25j  0.11-0.25j]
Для матрицы A 2  : определитель -  0.03 , ранг -  4 , собственные значения -  [0.86 0.65 0.45 0.12]
Для матрицы A 3  : определитель -  0.0 , ранг -  0 , собственные значения -  [0. 0. 0.]


#### Проанализируйте результаты

+ Для случайной матрицы (A1) ранг 5 - максимальный ранг ненулевых миноров, максимальное число, что логично и соответствует размеру ее стороны. Собственные значения сложно интерпретировать на текущем этапе
+ Для диагональной матрицы ранг равен 4 - логично, тк матрица 4х4. Элементы на диагонали - ненулевые. Определитль существенно ниже 0 тк по сути является произведением элементов на диагонали, а они все ниже 0. Собственные значения равны значениям на диагонали, что отражает особенность этой матрицы
+ Для нулевой матрицы определитель, ранг и собственные значения равны 0.